### ISSUE TITLE
More languages - Parallel languages corpus

### ISSUE THREAD

**Issue by AmitMY** [ranyadshalom/seinfeld_laugh_corpus#2]
Can you please add more languages to the corpus (for example, Hebrew)? The laugh track is a very nice way to sync translation files, and I will do it myself if it is not simple for you to like running a script.

I would like to use it for a character aware translation, a work I am doing with Prof. Yoav Goldberg, and if you already have the episodes files it will be a great help. Otherwise, I'll need to download all of the episodes and run everything from scratch, both for English and Hebrew.

Thanks

**Comment by ranyadshalom** [comment]
Hi Amit,
This is a great idea, however I will not have time to do it my self in the next few weeks. If you end up doing it, feel free to send me a pull request so that others will enjoy this addition.

Please note that I am currently modifying the corpus_creation module to support more shows, so it is better if you make sure that you always work on the latest available code.

**Comment by AmitMY** [comment]
I was under the impression it would just be to run `subtitle_getter` with `sublanguageid = heb`, and save both options.

I'll try to do it myself, after I download all of the seasons

**Comment by ranyadshalom** [comment]
It is not so simple.
You will not get character names, because the matching of the subtitles is done against an English screenplay.
What I would do is write a script that matches a current corpus file to a Hebrew subtitles file and replaces all the dialog.
